### ISSUE TITLE
Do you know what is wrong with this ?

### ISSUE THREAD

**Issue by Abnerminjian** [pariasm/vnlb#1]
Thank you very much for open source related code.When l complied the code ,there are two errors.l have tried several times,but l don't know how to solve it.

`shentu@shentu-Lenovo-Product:~/code/vnlb-master/build$ make
[ 11%] Built target iio

[ 22%] Built target tvl1flow

[ 33%] Built target tvl1flow-bin

[ 50%] Built target vidutils

[ 66%] Built target vnlb

[ 77%] Built target awgn

[ 83%] Linking CXX executable ../bin/vnlbayes

/usr/bin/ld: /usr/local/lib/liblapack.a(xerbla.o): undefined reference to symbol 

'_gfortran_string_len_trim@@GFORTRAN_1.0'

//usr/lib/x86_64-linux-gnu/libgfortran.so.3: error adding symbols: DSO missing from command line

collect2: error: ld returned 1 exit status

src/CMakeFiles/vnlbayes.dir/build.make:101: recipe for target 'bin/vnlbayes' failed

make[2]: *** [bin/vnlbayes] Error 1

CMakeFiles/Makefile2:389: recipe for target 'src/CMakeFiles/vnlbayes.dir/all' failed

make[1]: *** [src/CMakeFiles/vnlbayes.dir/all] Error 2

Makefile:127: recipe for target 'all' failed

make: *** [all] Error 2
`

**Comment by Abnerminjian** [comment]
Maybe the problem is the version of  LAPACKE.What is your version of LAPACKE used in the code?

**Comment by pariasm** [comment]
I was able to compiled it with the following versions of LAPACKE: 
- v 3.6.1 compiled from the source
- v 3.6.0 installed via apt-get in ubuntu 16.04 lts
- v 3.7.1 installed via apt-get in ubuntu 18.04 lts

**Comment by Abnerminjian** [comment]
lt still didn't work.

**Comment by Aithusa1113** [comment]
Hey, I have met the same problem. Have you solved it?

**Comment by pariasm** [comment]
No, I haven't. I can't reproduce the problem.
