### ISSUE TITLE
VideoNLB::computeBayesEstimate: insufficient patches for given rank/patch dimension

### ISSUE THREAD

**Issue by Qunxiang** [pariasm/vnlb#2]
Thank you so much for your excellent work. 

But I have met an error every time when I run the command 'vnlbayes -i /my/video/frame-%03d.png -f 1 -l 10 -sigma 10'

terminate called after throwing an instance of 'std::runtime_error'
  what():  VideoNLB::computeBayesEstimate: insufficient patches for given rank/patch dimension.
Aborted (core dumped)

Have you ever met it before or what can I do to solve this problem?

Thank you so much.

**Comment by pariasm** [comment]
This is weird. It is not suppose to happen with the default parameters. Could you send me the text output of the program?

**Comment by pariasm** [comment]
The reason might be that the number of threads is too large. Try reducing the number of threads by setting the OMP_NUM_THREADS enviroment variable before calling the program:
`$ export OMP_NUM_THREADS=4`

Even if this isn't the reason for the error, in my experience the code might run **slower** with such a high number of threads. Typically I use between 4 and 12.

Let me know if this helps.

**Comment by Qunxiang** [comment]
> number of threads

I've set the number of threads from 8 to 1, but it didn't help :(

**Comment by Qunxiang** [comment]
> The reason might be that the number of threads is too large. Try reducing the number of threads by setting the OMP_NUM_THREADS enviroment variable before calling the program:
> `$ export OMP_NUM_THREADS=4`
> 
> Even if this isn't the reason for the error, in my experience the code might run **slower** with such a high number of threads. Typically I use between 4 and 12.
> 
> Let me know if this helps.

I've set the number of threads from 8 to 1, but it didn't help :(

**Comment by Qunxiang** [comment]
> The reason might be that the number of threads is too large. Try reducing the number of threads by setting the OMP_NUM_THREADS enviroment variable before calling the program:
> `$ export OMP_NUM_THREADS=4`
> 
> Even if this isn't the reason for the error, in my experience the code might run **slower** with such a high number of threads. Typically I use between 4 and 12.
> 
> Let me know if this helps.

hey Arias, I am so happy to tell you that the problem has been solved since downloading the latest version of the code.  Sorry to bother you and thank you so much :)

**Comment by pariasm** [comment]
OK, it's good to hear that. Indeed the initial commit had a few bugs. I'm closing the issue.
