### ISSUE TITLE
How to compute VNLB-H 10*10*2?

### ISSUE THREAD

**Issue by yangting651995** [pariasm/vnlb#3]
Thank you for the  source.

There are two variants of the VNLB,VNLB-S and VNLB-H, with patch sizes 7×7×2 and 10×10×2.And the default parameter of the code is VNLB-H with patch sizes 7×7×2.

l want to run VNLB-H with patch sizes 10×10×2.l tred to enter the command like this on the test video tennis  ,but it didn't run.

` vnlb-gt.sh /my/video/frame-%03d.png 1 150 10 out-folder -px1 10 -px2 10`

 
So could you tell me how to run VNLB-H with patch sizes 10×10×2 and VNLB-S.

**Comment by pariasm** [comment]
For the moment, the code of this repository corresponds only to the VNLB-H version. To run it with 10x10x2 patches, if you use the patch script, you need to pass the parameters between quotes:

```./vnlb-gt.sh /my/video/frame-%03d.png 1 150 10 out-folder "-px1 10 -pt1 2 -px2 10 -pt2 2"```

**Comment by pariasm** [comment]
Did you manage to make it work? Let me know so I can close the issue.

**Comment by yangting651995** [comment]
Yes，l have made it work.Thanks for your answer.
