### ISSUE TITLE
Take noisy frames as input

### ISSUE THREAD

**Issue by axeldavy** [pariasm/vnlb#4]
The sigma parameter of vnlbayes gives this description:
"add noise of standard deviation sigma"

Which means we have to pass the non noisy frames as input.

Please make it possible to give noisy frames and the estimated sigma.

**Comment by pariasm** [comment]
The binary `vnlbayes` **does not** add noise. It assumes that the input sequence is noisy (with additive white Gaussian noise) of standard deviation sigma. The help comment about sigma was miss-leading, and I changed it now. Thanks for pointing that out.

Please check the helper scripts:
`vnlb.sh` takes as input a noisy sequence. It computes the optical flow and then runs the vnlb binary. 

`vnlb-gt.sh` is useful to evaluate the performance of the method: it takes as input a clean sequence (the ground truth), adds noise, calls `vnlb.sh` on the noisy sequence, and finally computes the PSNR and RMSE between the ground truth and the denoising output.
