### ISSUE TITLE
Default patch size ?

### ISSUE THREAD

**Issue by axeldavy** [pariasm/vnlb#5]
Hi,

The default patch size seems to be 7x7x2.

However in your paper "Video denoising via empirical Bayesian estimation of space-time patches", you compared 7x7x2 and 10x10x2 and shows that the latter has better performance.
I think this should be set the default.

**Comment by pariasm** [comment]
For grayscale I switch the default patch size to 10x10x2. For RGB it is still 7x7x2.

The reason I'm not using 10x10x2 for RGB is that I didn't tune the rest of the parameters for 10x10x2 (I did tune them for 10x10x2 patches using the VNLB-S variant, but this code implements the VNLB-H variant).
