### ISSUE TITLE
Optical flow

### ISSUE THREAD

**Issue by Aithusa1113** [pariasm/vnlb#6]
Hey, will the algorithm performs better when an optical flow is computed?

**Comment by pariasm** [comment]
Yes. You'll probably notice the difference in better recovery of details in moving objects (as long as the optical flow method correctly estimates their motion). The differences should be more noticeable for higher noise levels. Of course if your video is of a static scene, then the optical flow won't make a difference.

**Comment by Aithusa1113** [comment]
Hi, is the optical flow computed by the noisy frames or clean frames?  I run vnlb-gt.sh with clean frames for denoising tasks at different noise levels, should I remove the frame-%03d.flo files form "out-folder" after one task and compute again?

**Comment by pariasm** [comment]
The optical flow is computed between the noisy frames. And yes, you should remove the flo files if you change the noise, because the code doesn't re-compute the optical flow if the flo files are already in the output folder.
