### ISSUE TITLE
compiling issue in arch linux

### ISSUE THREAD

**Issue by chrisbgp** [pariasm/vnlb#7]
[ 66%] Linking CXX shared library ../../lib/libvnlb.so
/usr/bin/ld: cannot find CMakeFiles/vnlb.dir/LibMatrix.cpp.o: No such file or directory
collect2: error: ld returned 1 exit status
[ 66%] Built target vnlb
[ 72%] Building CXX object src/CMakeFiles/psnr.dir/psnr.cpp.o
[ 77%] Linking CXX executable ../bin/psnr
[ 77%] Built target psnr
[ 83%] Building CXX object src/CMakeFiles/awgn.dir/awgn.cpp.o
[ 88%] Linking CXX executable ../bin/awgn
[ 88%] Built target awgn
[ 94%] Building CXX object src/CMakeFiles/vnlbayes.dir/main_vnlb.cpp.o
make[2]: *** No rule to make target 'lib/libvnlb.so', needed by 'bin/vnlbayes'.  Stop.
[100%] Built target vnlbayes

# ls bin
awgn  psnr  tvl1flow  tvl1flow-seq.sh  vnlb-gt.sh  vnlb.sh

Everything but vnlbayes is compiling. Can you suggest a workaround? Thanks!

**Comment by pariasm** [comment]
Sorry, I can't reproduce that error. 

The problem comes from the linker not finding LibMatrix.cpp.o. This is strange because that file should have been generated in the earlier steps of the make (in particular in the 61%  step, see make output below). If it failed to compile LibMatrix.cpp it should have stopped the compilation at that step.

Do you have any other error or warnings earlier when you run cmake or make?

```
build(master)$ make
Scanning dependencies of target iio
[  5%] Building C object lib/iio/CMakeFiles/iio.dir/iio.c.o
[ 11%] Linking C static library libiio.a
[ 11%] Built target iio
Scanning dependencies of target tvl1flow-bin
[ 16%] Building C object lib/tvl1flow/CMakeFiles/tvl1flow-bin.dir/main.c.o
[ 22%] Linking C executable ../../bin/tvl1flow
[ 22%] Built target tvl1flow-bin
Scanning dependencies of target tvl1flow
[ 27%] Building C object lib/tvl1flow/CMakeFiles/tvl1flow.dir/tvl1flow_lib.c.o
[ 33%] Linking C static library libtvl1flow.a
[ 33%] Built target tvl1flow
Scanning dependencies of target vidutils
[ 38%] Building CXX object src/VidUtils/CMakeFiles/vidutils.dir/LibVideoT.cpp.o
[ 44%] Building C object src/VidUtils/CMakeFiles/vidutils.dir/mt19937ar.c.o
[ 50%] Linking CXX shared library ../../lib/libvidutils.so
[ 50%] Built target vidutils
Scanning dependencies of target vnlb
[ 55%] Building CXX object src/VNLBayes/CMakeFiles/vnlb.dir/VideoNLBayes.cpp.o
[ 61%] Building CXX object src/VNLBayes/CMakeFiles/vnlb.dir/LibMatrix.cpp.o                      <----- HERE
[ 66%] Linking CXX shared library ../../lib/libvnlb.so
[ 66%] Built target vnlb
Scanning dependencies of target awgn
[ 72%] Building CXX object src/CMakeFiles/awgn.dir/awgn.cpp.o
[ 77%] Linking CXX executable ../bin/awgn
[ 77%] Built target awgn
Scanning dependencies of target vnlbayes
[ 83%] Building CXX object src/CMakeFiles/vnlbayes.dir/main_vnlb.cpp.o
[ 88%] Linking CXX executable ../bin/vnlbayes
[ 88%] Built target vnlbayes
Scanning dependencies of target psnr
[ 94%] Building CXX object src/CMakeFiles/psnr.dir/psnr.cpp.o
[100%] Linking CXX executable ../bin/psnr
[100%] Built target psnr
```

**Comment by chrisbgp** [comment]
Thanks, I found a way to compile it on an ubuntu box. The first try was on a Arch Linux system, but that should? have worked too. Not sure what the cause was.
