### ISSUE TITLE
Benchmarking Code

### ISSUE THREAD

**Issue by gauenk** [pariasm/vnlb#9]
Hello,

Is there any benchmarking code to go along with this? Maybe the script used to run the experiments in the paper? I am getting a strangely low PSNR with the current code. I will keep testing, but I am unable to duplicate your impressive results.

**Comment by pariasm** [comment]
I'll upload a script to automate the computation of some results (hopefully next week).

But in the meantime, I re-computed one of the values in the table 2 (see image) of the paper and I got the same PSNR (32.55dB).
![image](https://user-images.githubusercontent.com/4415474/141335551-d5f7d798-83f4-4eb0-b1ed-0b688f2d13bf.png)

These are the commands I used
```
mkdir video_nlbayes3d_release
cd video_nlbayes3d_release/
git clone git@github.com:pariasm/vnlb.git .
mkdir build
cd build/
cmake ..
make
cd bin/
mkdir -p data/mobile-gray
cd data/
wget http://dev.ipol.im/~pariasm/video_nlbayes/videos/gmobile.avi . 
ffmpeg -i gmobile.avi -f image2 mobile-gray/%03d.png
cd ..
export OMP_NUM_THREADS=4
./vnlb-gt.sh data/mobile-gray/%03d.png 1 300 20 7x2/mobile_mono-s20/ "-px1 7 -pt1 2 -px2 7 -pt2 2"
grep Total 7x2/mobile_gray-s20/measures-deno
```

These are the values I got:
```
Total PSNR 32.546894
Total RMSE 6.014444
```

Notice that I'm limiting the number of OMP threads to 4. If you use too many the PSNR will drop.

**Comment by gauenk** [comment]
Wow thank you so much. This helps a lot.
